<?php
class CEmails
{
	function CEmails()
	{
		
	}
	
	function sendEmail($to, $subj, $mes)
	{
		// Headers
		$headers = "From: noreply@".$_REQUEST['sd']['host']."\r\n";
        $headers .= "Reply-To: noreply@".$_REQUEST['sd']['host']."\r\n";
        $headers .= "MIME-Version: 1.0\r\n";
        $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n"; 
        
		// Mail
		if (!mail($to, $subj, $mes, $headers))
			print "Error sending email";
	}
	
	function sendChgPassEmail($to)
	{
		$mes="<!doctype html><html><head><meta charset='UTF-8'><title>Untitled Document</title></head><center><bod><table width='100%' bgcolor='#f0f0f0'><tr><td align='center'><br><br><a href=\"http://www.chainrepublik.com\" style=\"font-size: 30px; font-family: Gotham, 'Helvetica Neue', Helvetica, Arial, 'sans-serif'; color: #aaaaaa; text-decoration: none; text-shadow: 1px 1px #ffffff\"><strong>ChainRepublik</strong></a><br><br><table width='500px'><tr><td height='600px' align='center' valign='top' bgcolor='#ffffff' style='border-radius: 10px; box-shadow: 1px 1px #dddddd;'><table width='450' border='0' cellspacing='0' cellpadding='0'><tbody><tr><td height='250' align='center'><img src='http://www.chainrepublik.com/pages/template/GIF/chg_pass.png' width='199' height='200' alt=''/></td></tr><tr><td height='50' align='center' style=\"font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 20px; color:#999999\">Account password change</td></tr><tr><td height='0' align='center'><hr></td></tr><tr><td height='140' align='center' style=\"font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 16px; color:#999999\">We have received a password change request for tour account on chainrepublik.com. Click the following button to change the password. If you believe your account activity is unauthorized, please get in touch with our support as soon as possible.</td></tr><tr><td height='50' align='center'><table width='450' border='0' cellspacing='0' cellpadding='0'>
	    <tbody><tr><td height='50' align='center' bgcolor='#009900' style='border-radius: 5px'><a href='http://www.chainrepublik.com' style=\"color: #ffffff; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 18px; text-decoration: none\"><div style='width: 100%' height='100%'>Change password</div></a></td></tr></tbody></table></td></tr><tr><td height='70' align='center' valign='bottom' style=\"color: #aaaaaa; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 12px;\">If you do not want to receive notifications from us, go to your account at chainrepublik.com and suspend receiving notifications from the Settings section.</td></tr></tbody></table></td></tr></table><br><br><br><br></td></tr></table></body></center></html>";
		
		// Send message
		$this->sendEmail($to, "chainrepublik.com - Password change confirmation", $mes);
	}
	
	function sendWthEmail($to, $amount, $cur, $uID)
	{
		$mes="<!doctype html><html><head><meta charset='UTF-8'><title>Untitled Document</title></head><center><bod><table width='100%' bgcolor='#f0f0f0'><tr><td align='center'><br><br><a href=\"http://www.chainrepublik.com\" style=\"font-size: 30px; font-family: Gotham, 'Helvetica Neue', Helvetica, Arial, 'sans-serif'; color: #aaaaaa; text-decoration: none; text-shadow: 1px 1px #ffffff\"><strong>ChainRepublik</strong></a><br><br><table width='500px'><tr><td height='600px' align='center' valign='top' bgcolor='#ffffff' style='border-radius: 10px; box-shadow: 1px 1px #dddddd;'><table width='450' border='0' cellspacing='0' cellpadding='0'><tbody><tr><td height='250' align='center'><img src='http://www.chainrepublik.com/pages/template/GIF/chg_pass.png' width='199' height='200' alt=''/></td></tr><tr><td height='50' align='center' style=\"font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 20px; color:#999999\">Withdraw Funds</td></tr><tr><td height='0' align='center'><hr></td></tr><tr><td height='140' align='center' style=\"font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 16px; color:#999999\">We have received a withdraw request of <strong style='color : $009900'>$amount $cur</strong> from your account. Click the following button to confirm this action. If you believe your account activity is unauthorized, please get in touch with our support as soon as possible.</td></tr><tr><td height='50' align='center'><table width='450' border='0' cellspacing='0' cellpadding='0'><tbody><tr><td height='50' align='center' bgcolor='#009900' style='border-radius: 5px'><a href='http://www.chainrepublik.com/confirm.php?code=$uID' style=\"color: #ffffff; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 18px; text-decoration: none\"><div style='width: 100%' height='100%'>Confirm withdraw</div></a></td></tr></tbody></table></td></tr><tr><td height='70' align='center' valign='bottom' style=\"color: #aaaaaa; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 12px;\">If you do not want to receive notifications from us, go to your account at chainrepublik.com and suspend receiving notifications from the Settings section.</td></tr></tbody></table></td></tr></table><br><br><br><br></td></tr></table></body></center></html>";
		
		// Send message
		$this->sendEmail($to, "chainrepublik.com - Withdraw request confirmation", $mes);
	}
	
	function sendWthConfirmedEmail($to, $amount, $cur)
	{
		$mes="<!doctype html><html><head><meta charset='UTF-8'><title>Untitled Document</title></head><center><bod><table width='100%' bgcolor='#f0f0f0'><tr><td align='center'><br><br><a href=\"http://www.chainrepublik.com\" style=\"font-size: 30px; font-family: Gotham, 'Helvetica Neue', Helvetica, Arial, 'sans-serif'; color: #aaaaaa; text-decoration: none; text-shadow: 1px 1px #ffffff\"><strong>ChainRepublik</strong></a><br><br><table width='500px'><tr><td height='600px' align='center' valign='top' bgcolor='#ffffff' style='border-radius: 10px; box-shadow: 1px 1px #dddddd;'><table width='450' border='0' cellspacing='0' cellpadding='0'><tbody><tr><td height='250' align='center'><img src='http://www.chainrepublik.com/pages/template/GIF/chg_pass.png' width='199' height='200' alt=''/></td></tr><tr><td height='50' align='center' style=\"font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 20px; color:#999999\">Withdraw Funds Confirmed</td></tr><tr><td height='0' align='center'><hr></td></tr><tr><td height='140' align='center' style=\"font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 16px; color:#999999\">You have successfully confirmed your withdraw request of $amount $cur. All withdraw requests are processed withing 24 hours. If you believe your account activity is unauthorized, please get in touch with our support as soon as possible.</td></tr><tr><td height='50' align='center'><table width='450' border='0' cellspacing='0' cellpadding='0'><tbody><tr><td height='50' align='center' bgcolor='#009900' style='border-radius: 5px'><a href='http://www.chainrepublik.com' style=\"color: #ffffff; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 18px; text-decoration: none\"><div style='width: 100%' height='100%'>Login for more details</div></a></td></tr></tbody></table></td></tr><tr><td height='70' align='center' valign='bottom' style=\"color: #aaaaaa; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 12px;\">If you do not want to receive notifications from us, go to your account at chainrepublik.com and suspend receiving notifications from the Settings section.</td></tr></tbody></table></td></tr></table><br><br><br><br></td></tr></table></body></center></html>";
		
		// Send message
		$this->sendEmail($to, "chainrepublik.com - Withdraw request confirmed", $mes);
	}
	
	function sendWthExecutedEmail($to, $amount, $cur)
	{
		$mes="<!doctype html><html><head><meta charset='UTF-8'><title>Untitled Document</title></head><center><bod><table width='100%' bgcolor='#f0f0f0'><tr><td align='center'><br><br><a href=\"http://www.chainrepublik.com\" style=\"font-size: 30px; font-family: Gotham, 'Helvetica Neue', Helvetica, Arial, 'sans-serif'; color: #aaaaaa; text-decoration: none; text-shadow: 1px 1px #ffffff\"><strong>ChainRepublik</strong></a><br><br><table width='500px'><tr><td height='600px' align='center' valign='top' bgcolor='#ffffff' style='border-radius: 10px; box-shadow: 1px 1px #dddddd;'><table width='450' border='0' cellspacing='0' cellpadding='0'><tbody><tr><td height='250' align='center'><img src='http://www.chainrepublik.com/pages/template/GIF/chg_pass.png' width='199' height='200' alt=''/></td></tr><tr><td height='50' align='center' style=\"font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 20px; color:#999999\">Withdraw Executed</td></tr><tr><td height='0' align='center'><hr></td></tr><tr><td height='140' align='center' style=\"font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 16px; color:#999999\">Your withdraw request has been successfully executed. We have send you $amount $cu. If you don't receive the coins / money within 5 minutes pls. get in touch with our support. If you believe your account activity is unauthorized, please get in touch with our support as soon as possible.</td></tr><tr><td height='50' align='center'><table width='450' border='0' cellspacing='0' cellpadding='0'><tbody><tr><td height='50' align='center' bgcolor='#009900' style='border-radius: 5px'><a href='http://www.chainrepublik.com' style=\"color: #ffffff; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 18px; text-decoration: none\"><div style='width: 100%' height='100%'>Login for more details</div></a></td></tr></tbody></table></td></tr><tr><td height='70' align='center' valign='bottom' style=\"color: #aaaaaa; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 12px;\">If you do not want to receive notifications from us, go to your account at chainrepublik.com and suspend receiving notifications from the Settings section.</td></tr></tbody></table></td></tr></table><br><br><br><br></td></tr></table></body></center></html>";
		
		// Send message
		$this->sendEmail($to, "chainrepublik.com - Withdraw request executed", $mes);
	}
	
	function sendMoneyReceivedEmail($to, $amount, $moneda)
	{
		$mes="<!doctype html><html><head><meta charset='UTF-8'><title>Untitled Document</title></head><center><bod><table width='100%' bgcolor='#f0f0f0'><tr><td align='center'><br><br><a href=\"http://www.chainrepublik.com\" style=\"font-size: 30px; font-family: Gotham, 'Helvetica Neue', Helvetica, Arial, 'sans-serif'; color: #aaaaaa; text-decoration: none; text-shadow: 1px 1px #ffffff\"><strong>ChainRepublik</strong></a><br><br><table width='500px'><tr><td height='600px' align='center' valign='top' bgcolor='#ffffff' style='border-radius: 10px; box-shadow: 1px 1px #dddddd;'><table width='450' border='0' cellspacing='0' cellpadding='0'><tbody><tr><td height='250' align='center'><img src='http://www.chainrepublik.com/pages/template/GIF/money_received.png' width='199' height='200' alt=''/></td></tr><tr><td height='50' align='center' style=\"font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 20px; color:#999999\">You have received <strong style='color:#009900'>".$amount." ".$moneda."</strong> </td></tr><tr><td height='0' align='center'><hr></td></tr><tr><td height='140' align='center' style=\"font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 16px; color:#999999\">We have good news. You have just received <span style='color:#009900'>".$amount." ".$moneda."</span> from an external address. We will credit your account as soon as the transaction gets confirmed. For Bitcoin we require 1 confirmation. For CRC we require 2 confirmations.</td></tr><tr><td height='50' align='center'><table width='450' border='0' cellspacing='0' cellpadding='0'><tbody><tr><td height='50' align='center' bgcolor='#009900' style='border-radius: 5px'><a href='http://www.chainrepublik.com' style=\"color: #ffffff; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 18px; text-decoration: none\"><div style='width: 100%' height='100%'>Login to check your account</div></a></td></tr></tbody></table></td></tr><tr><td height='70' align='center' valign='bottom' style=\"color: #aaaaaa; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 12px;\">If you do not want to receive notifications from us, go to your account at chainrepublik.com and suspend receiving notifications from the Settings section.</td></tr></tbody></table></td></tr></table><br><br><br><br></td></tr></table></body></center></html>";
		
		// Send message
		$this->sendEmail($to, "chainrepublik.com - You have received coins", $mes);
	}
	
	function sendRewardReceivedEmail($to, $amount)
	{
		$mes="<!doctype html><html><head><meta charset='UTF-8'><title>Untitled Document</title></head><center><bod><table width='100%' bgcolor='#f0f0f0'><tr><td align='center'><br><br><a href=\"http://www.chainrepublik.com\" style=\"font-size: 30px; font-family: Gotham, 'Helvetica Neue', Helvetica, Arial, 'sans-serif'; color: #aaaaaa; text-decoration: none; text-shadow: 1px 1px #ffffff\"><strong>ChainRepublik</strong></a><br><br><table width='500px'><tr><td height='600px' align='center' valign='top' bgcolor='#ffffff' style='border-radius: 10px; box-shadow: 1px 1px #dddddd;'><table width='450' border='0' cellspacing='0' cellpadding='0'><tbody><tr><td height='250' align='center'><img src='http://www.chainrepublik.com/pages/template/GIF/money_received.png' width='199' height='200' alt=''/></td></tr><tr><td height='50' align='center' style=\"font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 20px; color:#999999\">You have received <strong style='color:#009900'>".$amount."</strong> </td></tr><tr><td height='0' align='center'><hr></td></tr><tr><td height='140' align='center' style=\"font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 16px; color:#999999\">We have good news. You have just received <span style='color:#009900'>".$amount."</span> from an external address. We will credit your account as soon as the transaction gets confirmed. For Bitcoin we require 1 confirmation. For CRC we require 2 confirmations.</td></tr><tr><td height='50' align='center'><table width='450' border='0' cellspacing='0' cellpadding='0'><tbody><tr><td height='50' align='center' bgcolor='#009900' style='border-radius: 5px'><a href='http://www.chainrepublik.com' style=\"color: #ffffff; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 18px; text-decoration: none\"><div style='width: 100%' height='100%'>Login to check your account</div></a></td></tr></tbody></table></td></tr><tr><td height='70' align='center' valign='bottom' style=\"color: #aaaaaa; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-size: 12px;\">If you do not want to receive notifications from us, go to your account at chainrepublik.com and suspend receiving notifications from the Settings section.</td></tr></tbody></table></td></tr></table><br><br><br><br></td></tr></table></body></center></html>";
		
		// Send message
		$this->sendEmail($to, "chainrepublik.com - You have received a reward", $mes);
	}
}
?>